# armbands toml
modLoader="javafml"
loaderVersion="[36,)"
license="LGPLv3"

[[mods]]
modId="armbands"
version="${file.jarVersion}"
displayName="Armbands"
logoFile="icon.png"
credits=""
authors="Nano (thenamesnano)"
description='''
A mod that adds armbands to distinguish team members from other players.
'''

[[dependencies.armbands]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.armbands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
